### ISSUE TITLE
url show 'undefind' , when preview

### ISSUE THREAD

**Issue by yujiaqi** [HcySunYang/vuese#220]
When using  'vuese serve --open'  command, the address bar address is  'http://127.0.0.1:5000/#/undefind'. 

I found that in the function which is getFirstPath , the reduce method of the array has no return value.So firstRoute is  undefind.

**Comment by Viggo95** [comment]
@yujiaqi 
This error is usually due to the . /website does not generate a components directory

<br>

- Check the `./website/components` directory under your project to see if it's empty or doesn't exist at all
- Provide a screenshot of the vuese gen execution in your project

<br>

Normally, when you execute `vuese gen`

``` shell
.
├── src
│   ├── components
│   │   └── main.vue
│   └── lib
└── website
    ├── components
    │   └── MyComponent2.md
    └── index.html

```
<br>

Then run `vuese serve `,  it will output this 👇  in terminal
 ``` shell
✨ Server running at http://127.0.0.1:5000/#/components/MyComponent2
```

Then it will open the link  like this
![image](https://user-images.githubusercontent.com/22092110/108463734-da2f9600-72b9-11eb-81bc-77a092f8d34e.png)
