### ISSUE TITLE
SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by BuptStEve** [HcySunYang/vuese#63]
**Describe the bug**
* If default is `() => ({ a: 1, b: 2 })`. We got `SyntaxError: Unexpected token :`
* If default is `default: () => ({})` or `default: () => ({ a: 1 })`. We got `-`.
* If default is `default(){return{}}`. We got `default() {\n  return {};\n}`.

**To Reproduce**
```js
{
  props: {
    name: {
      default: () => ({ a: 1, b: 2 }),
    }
  },
}
```

**Expected behavior**
* No error.
* Add \` before and after the function code to avoid `\n`?

**Screenshots**
![image](https://user-images.githubusercontent.com/11501493/55711195-cd378f80-5a1e-11e9-9e9d-cf7a549032d4.png)

* With Vuepress
![image](https://user-images.githubusercontent.com/11501493/55712220-ee00e480-5a20-11e9-9e04-6b376ab848f5.png)

**Which version do you use:**
@vuese/parser: 2.1.3

**Comment by HcySunYang** [comment]
`@babel/generator 7.0` has a bug:
```js
const source = '() => ({ a: 1, b: 2 })'
const code = generate(source)  // () => { a: 1, b: 2 }  Lost Parens
```
It seems that `@babel/generator 7.4` solves this problem, so I tried to upgrade the version of `@babel/*` related dependencies, but I have encountered some problems: there is no corresponding update in [@types/*](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/babel__generator), which leads to more problems and needs a lot of Modifications, I think it's a more correct choice to wait until [@types/*](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/babel__generator) is updated.

Now my solution is to avoid interruptions caused by program errors, which means that the resolution of the default values may not be correct, so we recommend making things perfect by adding leading comments. E.g:

```js
{
  props: {
    name: {
      // `{ a: 1, b: 2 }`
      default: () => ({ a: 1, b: 2 }),
    }
  },
}
```

**Comment by HcySunYang** [comment]
BTW: Use `@vuese/parser@2.1.6`
